site_name: Notas Musicais
repo_url: https://github.com/leosousa84/notas-musicais
repo_name:  Leosousa84/notas-musicais
edit_uri: tree/main/docs

theme:
 name: material
 language: pt-BR
 logo: assets/notas.png
 favicon: assets/notas.png

 markdown_extensions:
  - attr_list

 extra_css:
  - stylesheets/extra.css
